name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag moviedb-api-test:$(date +%s) --tag  moviedb-api-test:latest
    - name: Run the Docker image
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      run: docker run --rm -v ${{ github.workspace }}/reports:/apitests/reports -e BEARER_TOKEN=$BEARER_TOKEN moviedb-api-test:latest

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: Test Report
        path: reports/report.html

  performance:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario: [staggered, burst, normal]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Locust
        run: |
          python -m pip install --upgrade pip
          pip install locust

      - name: Run Locust performance tests
        run: |
          locust -f performance/locustfile.py --headless --scenario=${{ matrix.scenario }} --only-summary --csv=locust/log

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: Performance Tests results
          path: locust
